### ISSUE TITLE
Inconsistent determinant coefficients

### ISSUE THREAD

**Issue by ferupp** [block-hczhai/pyblock3-preview#12]
While looking at states imported from block2 and comparing coefficients of determinants computed using

(i) the `get_csf_coefficients` method in block2
(ii) the `amplitude` method in pyblock3

I found different values (signs) for the same determinants.

I use the most recent versions of block2 (0.5.3rc11) and pyblock3 (0.2.9rc5). 

```
from pyscf import gto, scf
from pyblock2._pyscf.ao2mo import integrals as itg 
from pyblock2.driver.core import DMRGDriver, SymmetryTypes 
from pyblock3.block2.io import MPSTools

mol = gto.M(atom="N 0 0 0; N 0 0 1.1", basis="sto3g", symmetry="d2h", verbose=0) 
mf = scf.RHF(mol).run()

ncas, n_elec, spin, ecore, h1e, g2e, orb_sym = itg.get_rhf_integrals(mf, ncore=0, ncas=None, g2e_symm=8)

driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SZ) 
driver.initialize_system(n_sites=ncas, n_elec=n_elec, spin=spin, orb_sym=orb_sym)

mpo = driver.get_qc_mpo(h1e=h1e, g2e=g2e, ecore=ecore, iprint=0) 
ket = driver.get_random_mps(tag="GS", bond_dim=250, nroots=1)

bond_dims = [250] * 4 + [500] * 4
noises = [1e-4] * 4 + [1e-5] * 4 + [0]
thrds = [1e-10] * 8

energy = driver.dmrg(mpo, ket, n_sweeps=20, bond_dims=bond_dims, noises=noises, thrds=thrds, iprint=0)

det_a = [3, 3, 1, 3, 3, 3, 2, 0, 0, 3]

print(driver.get_csf_coefficients(ket, cutoff=0.01, given_dets=[det_a], iprint=0))

ket_block3 = MPSTools().from_block2(ket).to_non_flat().to_sliceable()
print(det_a, ket_block3.amplitude(det_a), "\n")

det_b = [3, 3, 2, 3, 3, 3, 1, 0, 0, 3]

print(driver.get_csf_coefficients(ket, cutoff=0.01, given_dets=[det_b], iprint=0)) 
print(det_b, ket_block3.amplitude(det_b))
```
Output:
```
(array([[3, 3, 1, 3, 3, 3, 2, 0, 0, 3]], dtype=uint8), array([-0.01460361])) 
[3, 3, 1, 3, 3, 3, 2, 0, 0, 3] 0.014603614310254861

(array([[3, 3, 2, 3, 3, 3, 1, 0, 0, 3]], dtype=uint8), array([0.01460361])) 
[3, 3, 2, 3, 3, 3, 1, 0, 0, 3] -0.014603612440786387
```

I couldn't find anything about a change in convention from block2 to pyblock3 of what '1' and '2' represent, so I assume this behavior is not intended?

Thanks

**Comment by hczhai** [comment]
Thanks for reporting this problem. The convention for 1 and 2 used in ``block2`` and ``pyblock3`` is indeed different.

1. The ``block2`` code uses "1=alpha" and "2=beta" as explained in https://block2.readthedocs.io/en/latest/api/pyblock2.html#pyblock2.driver.core.DMRGDriver.get_csf_coefficients.
2. The convention for the ``pyblock3`` code is given by the ordering of quantum numbers, which can be printed as:

```python3
>>> print(sorted(ket_block3.tensors[0].infos[1]))
[< N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >, < N=1 SZ=1/2 PG=0 >, < N=2 SZ=0 PG=0 >]
```

So the convention is "1=beta" (SZ=-1/2) and "2=alpha" (SZ=1/2).

3. If you want to enforce the same convention in ``block2`` and ``pyblock3``, you can add the following in your script

```python3
import pyblock3.algebra.symmetry, block2
pyblock3.algebra.symmetry.SZ = block2.SZ
```

**before** the line

```python3
from pyblock3.block2.io import MPSTools
```

(or at the very beginning of your script). This will change the ordering of quantum numbers in ``pyblock3`` to match that in ``block2``.

**Comment by ferupp** [comment]
Thank you very much for the quick and very clear answer!
